# Generated by Django 3.1.2 on 2020-10-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201031_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeprojectdetail',
            name='tools_used',
        ),
        migrations.AddField(
            model_name='resumeproject',
            name='tools_used',
            field=models.ManyToManyField(to='resume.ToolsUsed', verbose_name='Tools Used'),
        ),
    ]
