# Generated by Django 3.1.3 on 2020-11-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20201107_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeproject',
            name='git_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Git Link'),
        ),
        migrations.CreateModel(
            name='RelatedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=50, verbose_name='Link Name')),
                ('link_url', models.CharField(max_length=250, verbose_name='Link')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resumeproject')),
            ],
            options={
                'verbose_name': 'RelatedLinks',
                'verbose_name_plural': 'RelatedLinkss',
            },
        ),
    ]
